configName: pic32cz_ca90_curiosity_ultra
folderName: pic32cz_ca90_curiosity_ultra
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: PIC32CZ8110CA90208
projectName: i2c_eeprom_emulation_pic32cz_ca90_curiosity_ultra
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CZ-CA_DFP\0.0.62\CA90\atdf\PIC32CZ8110CA90208.atdf
