format_version: v1.0
type: UniqueComponent
attributes: {id: fcw}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '260', y: '20', id: fcw}
