format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: RTC_MODE0_MATCHCLR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: RTC_MODE0_TIMER_COMPARE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '256'}
  - type: Hex
    attributes: {id: RTC_MODE0_TIMER_COMPARE1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '256'}
- type: ElementPosition
  attributes: {x: '298', y: '116', id: rtc}
