format_version: v1.0
type: UniqueComponent
attributes: {id: sqi1}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SQI_CLKDIV}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Comment
    attributes: {id: SQI_CLK_DIV_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** SQI Clock Frequency Is Set To 50000000 for GCLK
            Frequency At 100000000'}
- type: ElementPosition
  attributes: {x: '440', y: '19', id: sqi1}
