configName: pic32cz_ca80_curiosity_ultra
folderName: pic32cz_ca80_curiosity_ultra
format_version: v1.0
frameworkPath: ..\..\..\..
processor: PIC32CZ8110CA80208
projectName: adc_blocking_pic32cz_ca80_curiosity_ultra
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CZ-CA80_DFP\1.0.14\CA80\atdf\PIC32CZ8110CA80208.atdf
